#line 1 "src/lexer.c"

#line 3 "src/lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 88
#define YY_END_OF_BUFFER 89
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[376] =
    {   0,
        0,    0,   89,   87,   10,    9,   87,   87,   87,   87,
       87,   87,   87,   87,   84,   84,   87,   87,   87,   87,
       79,   87,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       87,    8,   10,   61,    0,   85,    0,   64,   76,    0,
        0,   68,   70,   66,   71,   67,   59,    0,    1,   69,
        0,   83,   84,    0,   84,    0,   58,   74,   62,   60,
       63,   75,   79,   78,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   24,   79,   79,   79,   79,   79,   79,
       79,   79,   22,   79,   79,   79,   79,   79,   79,   79,

       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   77,   65,    8,    8,    8,    8,    8,   86,    0,
        0,    1,   80,   83,   82,   81,   72,   73,   79,   79,
       30,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   26,   79,   79,   38,   79,   79,
       43,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
        8,    8,    8,    8,    8,    2,    0,   80,   82,   81,
       79,   79,   41,   79,   36,   42,   79,   79,   79,   79,
       79,   79,   23,   13,   79,   79,   79,   29,   79,   79,

       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   49,   54,   79,   79,   79,   40,   79,   79,    8,
        8,    8,    8,    8,    0,   80,   31,   79,   27,   11,
       51,   79,   79,   79,   79,   55,   39,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   14,   79,   79,   25,    8,    8,    8,    8,
        8,   79,   79,   79,   79,   79,   44,   79,   57,   79,
       20,   79,   79,   79,   79,   15,   79,   21,   53,   79,
       12,   35,   79,   79,   79,    8,    0,    8,    8,    8,
        8,    8,   32,   79,   79,   79,   37,   79,   79,   56,

       79,   16,   79,   79,   79,   19,   50,   79,    0,    8,
        7,    8,    8,    8,    8,   79,   79,   28,   79,   79,
       52,   79,   79,   79,   33,    0,    8,    8,    8,    8,
       79,   79,   79,   18,   17,   79,   79,    8,    8,    8,
        8,    5,    8,   79,   47,   79,   79,   79,    8,    8,
        5,    6,   79,   79,   79,   45,    8,    4,    8,    8,
        6,    6,   34,   46,   79,    4,    8,   79,    8,    3,
       79,    3,   79,   48,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    1,    8,    9,    1,
        1,   10,   11,    1,   12,   13,   14,   15,   16,   17,
       17,   17,   17,   17,   17,   18,   18,   19,    1,   20,
       21,   22,    1,    1,   23,   24,   23,   23,   25,   26,
       27,   27,   27,   27,   27,   28,   27,   27,   27,   27,
       27,   27,   27,   27,   28,   27,   27,   29,   27,   27,
        1,   30,    1,   31,   32,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   27,   42,   43,   44,   45,
       46,   47,   27,   48,   49,   50,   51,   52,   53,   54,
       55,   56,    1,   57,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[58] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    4,    4,    4,    4,    1,    1,
        1,    1,    4,    4,    4,    4,    5,    5,    5,    1,
        1,    5,    4,    4,    4,    4,    4,    4,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    1
    } ;

static const flex_int16_t yy_base[396] =
    {   0,
        0,  736,  742,  744,   56,  744,  720,   53,   53,  710,
      718,   51,   54,   57,   71,   64,  719,   43,  716,   47,
        0,  715,  703,  685,   45,   63,   64,   59,   65,  687,
       52,   79,  685,   22,  694,   76,   80,  685,   77,  689,
       64,   92,  129,  744,  118,  744,    0,  744,  744,  719,
      129,  744,  744,  744,  744,  744,  744,  717,    0,  744,
      134,  140,  146,  121,  126,    0,  744,  705,  744,  744,
      744,  704,    0,  744,   94,  680,  677,  685,  672,  687,
      686,  673,   96,    0,  672,  667,  664,  671,  667,  664,
      670,  660,    0,  659,  116,  655,  664,  669,   99,  671,

      126,  648,  132,  662,  661,  650,  653,  658,  650,  129,
      653,  744,  744,    0,  169,  643,  106,  647,  744,  669,
      165,    0,  177,  145,  183,  162,  744,  744,  625,  623,
        0,  621,  626,  617,  601,  595,  132,  596,  582,  580,
      570,  560,  554,  569,    0,  564,  554,    0,  562,  557,
        0,  554,  548,  543,  544,  550,  547,  540,  553,  539,
      537,  537,  537,  548,  547,  537,  532,  545,  547,  534,
      202,  525,  521,  524,  525,  744,  212,  744,  182,  188,
      528,  528,    0,  524,    0,    0,  516,  514,  522,  500,
      497,  502,    0,    0,  508,  494,  498,    0,  493,  489,

      493,  506,  505,  500,  495,  485,  486,  487,  491,  496,
      495,    0,    0,  493,  483,  476,    0,  476,  488,  206,
      479,  473,  477,  470,  220,  225,  486,  484,    0,    0,
      484,  470,  471,  472,  467,    0,    0,  471,  459,  457,
      387,  383,  382,  396,  395,  392,  383,  389,  391,  375,
      384,  386,    0,  389,  380,    0,  203,  384,  368,  381,
      376,  384,  365,  379,  362,  362,    0,  376,    0,  377,
        0,  361,  360,  368,  354,    0,  355,    0,    0,  370,
        0,    0,  363,  357,  352,  241,  388,  198,  391,  344,
      378,  330,    0,  334,  341,  336,    0,  340,  336,    0,

      322,    0,  332,  321,  332,    0,    0,  329,  219,  243,
      744,  263,  328,  246,  319,  320,  313,    0,  326,  323,
        0,  323,  310,  324,    0,  247,  320,  354,  349,  352,
      316,  302,  316,    0,    0,  311,  298,  251,  377,  434,
      340,    0,  343,  312,    0,  294,  288,  287,  330,  491,
        0,  333,  291,  216,  230,    0,  255,    0,  252,  548,
      258,    0,    0,    0,  224,    0,  250,  222,  226,    0,
      158,    0,  128,    0,  744,  605,  610,  612,  617,  622,
      627,   61,  632,  637,  642,  647,  652,  657,  662,  667,
      672,  677,  682,  687,  692

    } ;

static const flex_int16_t yy_def[396] =
    {   0,
      375,    1,  375,  375,  375,  375,  375,  376,  375,  377,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      378,  375,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      375,  379,  375,  375,  376,  375,  376,  375,  375,  375,
      377,  375,  375,  375,  375,  375,  375,  380,  381,  375,
      375,  375,  375,  375,  375,  382,  375,  375,  375,  375,
      375,  375,  378,  375,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,

      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  375,  375,  379,  379,  379,  379,  379,  375,  380,
      380,  381,  375,  375,  375,  382,  375,  375,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      379,  379,  379,  379,  379,  375,  375,  375,  375,  375,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,

      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  379,
      379,  379,  379,  379,  375,  375,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  383,  379,  379,  379,
      379,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  383,  384,  379,  379,  379,
      379,  379,  378,  378,  378,  378,  378,  378,  378,  378,

      378,  378,  378,  378,  378,  378,  378,  378,  375,  379,
      375,  375,  379,  379,  379,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  375,  385,  379,  386,  379,
      378,  378,  378,  378,  378,  378,  378,  379,  385,  375,
      386,  387,  388,  378,  378,  378,  378,  378,  389,  390,
      387,  391,  378,  378,  378,  378,  389,  392,  379,  390,
      391,  393,  378,  378,  378,  392,  394,  378,  394,  395,
      378,  395,  378,  378,    0,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375

    } ;

static const flex_int16_t yy_nxt[802] =
    {   0,
        4,    5,    6,    5,    7,    8,    4,    9,   10,   11,
       12,   13,    4,   14,   15,   16,   16,   16,   17,   18,
       19,   20,   21,   21,   21,   21,   21,   21,   21,    4,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   21,
       31,   21,   21,   21,   32,   33,   34,   35,   36,   37,
       38,   39,   40,   21,   21,   21,   41,   43,   46,   43,
       48,   53,   68,   69,  126,   55,   58,   71,   72,   99,
       59,   54,  100,   49,   56,   57,   61,   60,   63,   63,
       63,   63,   47,   61,  112,   62,   62,   62,   63,   93,
       77,   65,   78,  115,   64,   79,   94,   88,   65,   66,

       83,   86,   80,   87,   64,   81,   65,   89,   82,   84,
       90,   95,   91,   65,   65,   96,  102,  109,   85,  105,
      113,   65,  110,   46,   66,  103,  129,  106,  104,   97,
       43,  375,   43,  138,  107,  125,  125,   50,  139,  154,
      116,  117,  173,  118,  155,  130,  174,   47,  123,  123,
      123,  123,   61,   65,   62,   62,   62,   63,   61,  149,
       63,   63,   63,   63,  160,  150,  157,  124,   65,  168,
      115,  169,  124,   65,  121,  158,   65,  374,  176,  161,
      188,  189,  124,  171,  171,  171,  171,  124,   65,  180,
      124,  123,  123,  123,  123,  124,   65,  125,  125,  310,

      311,  177,  178,  220,  180,  287,  373,  220,  288,  179,
      179,  257,  180,  177,  178,  180,  171,  171,  171,  171,
      326,  311,  225,  225,  179,  179,  226,  226,  226,  226,
      180,  370,  179,  179,  226,  226,  226,  226,  180,  226,
      226,  226,  226,  287,  310,  311,  288,  314,  326,  311,
      178,  329,  338,  359,  371,  370,  349,  367,  368,  362,
      358,  365,  178,  114,  312,  364,  114,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  114,  327,  327,  327,  327,  327,
      327,  327,  114,  114,  327,  327,  327,  327,  327,  327,

      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  114,
      114,  338,  363,  114,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  362,  358,  356,  355,  114,  114,
      114,  114,  354,  353,  343,  342,  348,  347,  346,  114,
      114,  345,  344,  343,  342,  340,  337,  336,  335,  334,
      333,  332,  331,  330,  328,  325,  324,  323,  322,  321,
      320,  319,  318,  317,  316,  315,  114,  114,  338,  314,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  313,  312,  309,  308,  114,  114,  114,  114,  307,

      306,  305,  304,  303,  302,  301,  114,  114,  300,  299,
      298,  297,  296,  295,  294,  293,  292,  291,  290,  289,
      285,  284,  283,  282,  281,  280,  279,  278,  277,  276,
      275,  274,  273,  114,  114,  340,  272,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  350,  350,  350,  350,
      350,  350,  350,  114,  114,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      114,  114,  359,  271,  114,  114,  114,  114,  114,  114,

      114,  114,  114,  114,  114,  270,  269,  268,  267,  114,
      114,  114,  114,  266,  265,  264,  263,  262,  261,  260,
      114,  114,  259,  258,  256,  255,  254,  253,  252,  251,
      250,  249,  248,  247,  246,  245,  244,  243,  242,  241,
      240,  239,  238,  237,  236,  235,  234,  114,  114,  359,
      233,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  114,  232,  231,  230,  229,  114,  114,  114,  114,
      228,  227,  224,  223,  222,  221,  219,  114,  114,  218,
      217,  216,  215,  214,  213,  212,  211,  210,  209,  208,
      207,  206,  205,  204,  203,  202,  201,  200,  199,  198,

      197,  196,  195,  194,  114,   45,  193,   45,   45,   45,
       50,   50,  192,   50,   50,   73,   73,  114,  191,  114,
      114,  114,  120,  120,  120,  120,  120,  122,  190,  122,
      122,  122,  286,  286,  286,  286,  286,  287,  287,  287,
      287,  287,  339,  187,  339,  339,  339,  341,  186,  341,
      341,  341,  351,  185,  351,  351,  351,  352,  184,  352,
      352,  352,  357,  183,  357,  357,  357,  360,  182,  360,
      360,  360,  361,  181,  361,  361,  361,  366,  121,  366,
      366,  366,  362,  175,  362,  362,  362,  369,  172,  369,
      369,  369,  372,  170,  372,  372,  372,  167,  166,  165,

      164,  163,  162,  159,  156,  153,  152,  151,  148,  147,
      146,  145,  144,  143,  142,  141,  140,  137,  136,  135,
      134,  133,  132,  131,  128,  127,  121,  119,  111,  108,
      101,   98,   92,   76,   75,   74,   70,   67,   52,   51,
       44,  375,   42,    3,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,

      375
    } ;

static const flex_int16_t yy_chk[802] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    8,    5,
        9,   12,   18,   18,  382,   13,   14,   20,   20,   34,
       14,   12,   34,    9,   13,   13,   16,   14,   16,   16,
       16,   16,    8,   15,   41,   15,   15,   15,   15,   31,
       25,   16,   25,   42,   15,   26,   31,   29,   15,   15,

       27,   28,   26,   28,   15,   26,   16,   29,   26,   27,
       29,   32,   29,   15,   16,   32,   36,   39,   27,   37,
       41,   15,   39,   45,   15,   36,   75,   37,   36,   32,
       43,   51,   43,   83,   37,   64,   64,   51,   83,   99,
       42,   42,  117,   42,   99,   75,  117,   45,   61,   61,
       61,   61,   62,   65,   62,   62,   62,   62,   63,   95,
       63,   63,   63,   63,  103,   95,  101,   62,   65,  110,
      115,  110,  124,   63,  121,  101,   65,  373,  121,  103,
      137,  137,   62,  115,  115,  115,  115,  124,   63,  126,
       62,  123,  123,  123,  123,  124,   63,  125,  125,  288,

      288,  123,  123,  171,  126,  257,  371,  220,  257,  179,
      125,  220,  126,  123,  123,  180,  171,  171,  171,  171,
      309,  309,  177,  177,  179,  125,  177,  177,  177,  177,
      180,  369,  179,  125,  225,  225,  225,  225,  180,  226,
      226,  226,  226,  286,  310,  310,  286,  314,  326,  326,
      226,  314,  338,  359,  368,  367,  338,  359,  365,  361,
      357,  355,  226,  312,  312,  354,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,

      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      327,  327,  353,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  352,  349,  348,  347,  327,  327,
      327,  327,  346,  344,  343,  341,  337,  336,  333,  327,
      327,  332,  331,  330,  329,  328,  324,  323,  322,  320,
      319,  317,  316,  315,  313,  308,  305,  304,  303,  301,
      299,  298,  296,  295,  294,  292,  327,  339,  339,  291,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  290,  289,  287,  285,  339,  339,  339,  339,  284,

      283,  280,  277,  275,  274,  273,  339,  339,  272,  270,
      268,  266,  265,  264,  263,  262,  261,  260,  259,  258,
      255,  254,  252,  251,  250,  249,  248,  247,  246,  245,
      244,  243,  242,  339,  340,  340,  241,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  350,  350,  240,  350,  350,  350,  350,  350,  350,

      350,  350,  350,  350,  350,  239,  238,  235,  234,  350,
      350,  350,  350,  233,  232,  231,  228,  227,  224,  223,
      350,  350,  222,  221,  219,  218,  216,  215,  214,  211,
      210,  209,  208,  207,  206,  205,  204,  203,  202,  201,
      200,  199,  197,  196,  195,  192,  191,  350,  360,  360,
      190,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  189,  188,  187,  184,  360,  360,  360,  360,
      182,  181,  175,  174,  173,  172,  170,  360,  360,  169,
      168,  167,  166,  165,  164,  163,  162,  161,  160,  159,
      158,  157,  156,  155,  154,  153,  152,  150,  149,  147,

      146,  144,  143,  142,  360,  376,  141,  376,  376,  376,
      377,  377,  140,  377,  377,  378,  378,  379,  139,  379,
      379,  379,  380,  380,  380,  380,  380,  381,  138,  381,
      381,  381,  383,  383,  383,  383,  383,  384,  384,  384,
      384,  384,  385,  136,  385,  385,  385,  386,  135,  386,
      386,  386,  387,  134,  387,  387,  387,  388,  133,  388,
      388,  388,  389,  132,  389,  389,  389,  390,  130,  390,
      390,  390,  391,  129,  391,  391,  391,  392,  120,  392,
      392,  392,  393,  118,  393,  393,  393,  394,  116,  394,
      394,  394,  395,  111,  395,  395,  395,  109,  108,  107,

      106,  105,  104,  102,  100,   98,   97,   96,   94,   92,
       91,   90,   89,   88,   87,   86,   85,   82,   81,   80,
       79,   78,   77,   76,   72,   68,   58,   50,   40,   38,
       35,   33,   30,   24,   23,   22,   19,   17,   11,   10,
        7,    3,    2,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,

      375
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/lexer.l"
#line 2 "src/lexer.l"
/*
 * lexer.l -- flex scanner.
 *

 * The interesting  part is IDENTIFIER classification  and the COLONCOLON
 * rule  right  below  it:  together  they  implement  the  "lexer  hack"
 * (deciding TYPE_NAME vs IDENTIFIER by consulting the symbol table) plus
 * qualified- name  (`v32::Timer`) support,  entirely in scan  order. See
 * the long comment on symtab_arm_qualifier()  in symtab.h for *why* this
 * lives here and not in a parser reduction action.
 *
 * SIMPLIFICATION:  no real  preprocessor.  Real C++  source needs  macro
 * expansion and conditional compilation handled before this scanner ever
 * sees it -- neither happens here. As an interim measure, though, a line
 * starting  with '#'  is  no longer  silently  discarded: it's  captured
 * verbatim (see g_preprocessor_lines, driver.h) so codegen.c can re-emit
 * it at  the top of the  generated file, ahead of  everything else. This
 * means a `#include "video.h"` a  person actually wrote now survives the
 * round trip  instead of having  to be  manually re-added by  hand every
 * time -- but it is still just pass-through, not preprocessing: no macro
 * expansion,  no  #include  resolution,  no  #ifdef  evaluation,  and  a
 * captured  #ifdef/#endif  pair  doesn't  actually  gate  anything  this
 * scanner sees, since it never interprets what was captured at all.
 *
 * As of  the include  pre-scan (see  prescan.c/prescan.h, run  by main.c
 * before  yyparse),  `#include`  lines  targeting  .hpp/.cpp  files  are
 * resolved  and expanded  into  the source  stream  BEFORE this  scanner
 * ever  sees  them  -- so  this  scanner  only  ever  lays eyes  on  the
 * pass-through  kind (.h/system  includes). The  line markers  that keep
 * g_lex_lineno/g_current_filename  honest   across  that   splicing  are
 * consumed by the dedicated rule below, and everything else about #-line
 * handling here is unchanged.
 *
 * ONE exception to "every `#`-line  is just passed through unread": cart
 * hints  (`#texture  NAME "file.png"`  /  `#sound  NAME "file.wav"`),  a
 * targeted special-case  recognized directly below,  NOT the start  of a
 * general  preprocessor  -- these  two  specific  forms get  parsed  for
 * their NAME/filename and registered (see g_cart_textures/g_cart_sounds,
 * driver.h),  instead of  falling  through to  the generic  pass-through
 * above. Modeled  directly on v32lua's own  `--#texture`/`--#sound` cart
 * hints.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "driver.h"
#include "parser.h"
#include "prescan.h" /* line-marker consumption -- see the new rule below */

/* Suppresses a warning in flex's OWN generated scanning machinery
 * (yy_get_next_buffer's buffer-resize check compares yy_size_t, an
 * unsigned type, against a plain int) -- not anything this project's
 * own code does; nothing here to fix on this project's side, since the
 * comparison lives entirely inside code flex itself emits below this
 * point, regenerated fresh from the flex skeleton every time and never
 * hand-edited. Confirmed present since the very first working build of
 * this project, mentioned in this file's own header comment as a known,
 * pre-existing, not-our-code issue from day one -- silencing it here
 * finally addresses the actual warning text directly, at the one place
 * that can, rather than continuing to just document it as expected in
 * every build report. No matching `#pragma ... pop` -- this generated
 * file is compiled standalone, never `#include`d elsewhere, so the
 * pragma's effect ending at end-of-file is exactly the intended scope. */
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wsign-compare"

/* Remembers the Symbol* (if any) resolved for the most recently scanned
 * IDENTIFIER/TYPE_NAME token, so that if the *next* token turns out to be
 * "::", we know what to arm the qualifier context with. Reset to NULL by
 * every other token so stale state can't leak across unrelated tokens
 * (e.g. "foo ; bar :: baz" must not treat foo as bar's qualifier). */
static Symbol *g_last_ident_sym = NULL;

#define YY_USER_ACTION \
    yylloc.first_line = yylloc.last_line = g_lex_lineno;

/* Appends one cart resource (a `#texture`/`#sound` hint) to `list`,
 * keeping id == list position exactly the way v32lua's own
 * cart_resource_append does (confirmed from its actual source) -- the
 * resource's id is never stored explicitly anywhere; it's always just
 * "whatever position this entry ends up at in the list," read back out
 * at both #define-emission time (codegen.c) and XML-emission time
 * (cartxml.c). */
static void register_cart_resource(CartResourceList *list, const char *name, const char *filename) {
    if (list->count == list->capacity) {
        list->capacity = list->capacity ? list->capacity * 2 : 8;
        list->items = realloc(list->items, sizeof(CartResource) * (size_t)list->capacity);
    }
    list->items[list->count].name = strdup(name);
    list->items[list->count].filename = strdup(filename);
    list->count++;
}
#line 844 "src/lexer.c"
#define YY_NO_INPUT 1
#line 846 "src/lexer.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 104 "src/lexer.l"


#line 1067 "src/lexer.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 376 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 744 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 106 "src/lexer.l"
{ /* line comment, discard */ }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 107 "src/lexer.l"
{ /* block comment, discard */ }
	YY_BREAK
/* Cart hints -- `#texture NAME "file.png"` / `#sound NAME "file.wav"`.
     * Matched BEFORE the generic "#"-line pass-through rule below,
     * deliberately: both would otherwise match the same full line (same
     * length), and flex's own "first rule wins on a length tie" behavior
     * means ORDER in this file is what actually decides which one a
     * cart hint gets recognized by -- these have to come first, or every
     * `#texture`/`#sound` line would just fall through to plain,
     * unrecognized pass-through instead. NAME is captured exactly as
     * written -- upper, lower, or mixed case, never forced to any
     * particular one. Does NOT also add the line to
     * g_preprocessor_lines -- a recognized cart hint is translated into
     * a `#define`, not passed through verbatim; only a genuinely
     * unrecognized `#`-line falls through to that. */
case 3:
YY_RULE_SETUP
#line 122 "src/lexer.l"
{
    char name[128] = {0};
    char filename[256] = {0};
    if (sscanf(yytext, "#texture %127s \"%255[^\"]\"", name, filename) == 2) {
        register_cart_resource(&g_cart_textures, name, filename);
    }
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 130 "src/lexer.l"
{
    char name[128] = {0};
    char filename[256] = {0};
    if (sscanf(yytext, "#sound %127s \"%255[^\"]\"", name, filename) == 2) {
        register_cart_resource(&g_cart_sounds, name, filename);
    }
}
	YY_BREAK
/* `#title "..."` / `#version ...` -- same "matched before the
     * generic pass-through, so it's recognized instead of just carried
     * through verbatim" reasoning as #texture/#sound above. title is
     * quoted (may contain spaces); version is a bare token (matching
     * v32lua's own "--#version 1.1", never quoted there either). Frees
     * any PREVIOUS value before overwriting -- a program with more than
     * one #title/#version simply keeps the last one seen, the same
     * "last write wins" behavior v32lua's own title/version hints have
     * (they just overwrite the same fixed-size buffer each time). */
case 5:
YY_RULE_SETUP
#line 147 "src/lexer.l"
{
    char title[256] = {0};
    if (sscanf(yytext, "#title \"%255[^\"]\"", title) == 1) {
        free(g_cart_title);
        g_cart_title = strdup(title);
    }
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 155 "src/lexer.l"
{
    char version[64] = {0};
    if (sscanf(yytext, "#version %63s", version) == 1) {
        free(g_cart_version);
        g_cart_version = strdup(version);
    }
}
	YY_BREAK
/* Line marker emitted by prescan.c (see prescan.h): `# N "file"`.
     * Consumed HERE, never passed through, because it is this
     * project's own bookkeeping, not the person's source. Sets
     * g_lex_lineno directly to N rather than N-1 because this
     * pattern swallows the marker's own newline -- the \n rule's
     * increment never runs for this line, so the next content line
     * is already counted as N. g_current_filename is re-pointed at
     * an interned copy (see prescan_intern_filename) so the storage
     * stays valid for the rest of the run. */
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 172 "src/lexer.l"
{
    int line_no;
    char fname[512];
    if (sscanf(yytext, "# %d \"%511[^\"]\"", &line_no, fname) == 2) {
        g_lex_lineno = line_no;
        g_current_filename = prescan_intern_filename(fname);
    }
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 181 "src/lexer.l"
{
    /* Preprocessor pass-through -- see this file's own header comment
     * and driver.h's PreprocessorLines for the full reasoning. Grows
     * g_preprocessor_lines by one and stores this line's text verbatim,
     * in original order; still returns no token, so the parser's own
     * grammar is completely unaffected by this -- codegen.c is the only
     * thing that ever reads this list. */
    if (g_preprocessor_lines.count == g_preprocessor_lines.capacity) {
        g_preprocessor_lines.capacity = g_preprocessor_lines.capacity ? g_preprocessor_lines.capacity * 2 : 8;
        g_preprocessor_lines.lines = realloc(g_preprocessor_lines.lines,
                                              sizeof(char *) * (size_t)g_preprocessor_lines.capacity);
    }
    g_preprocessor_lines.lines[g_preprocessor_lines.count++] = strdup(yytext);
}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 196 "src/lexer.l"
{ g_lex_lineno++; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 197 "src/lexer.l"
{ /* whitespace */ }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 199 "src/lexer.l"
{ g_last_ident_sym = NULL; return CLASS; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 200 "src/lexer.l"
{ g_last_ident_sym = NULL; return STRUCT; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 201 "src/lexer.l"
{ g_last_ident_sym = NULL; return ENUM; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 202 "src/lexer.l"
{ g_last_ident_sym = NULL; return UNION; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 203 "src/lexer.l"
{ g_last_ident_sym = NULL; return PUBLIC; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 204 "src/lexer.l"
{ g_last_ident_sym = NULL; return PRIVATE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 205 "src/lexer.l"
{ g_last_ident_sym = NULL; return PROTECTED; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 206 "src/lexer.l"
{ g_last_ident_sym = NULL; return NAMESPACE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 207 "src/lexer.l"
{ g_last_ident_sym = NULL; return TYPEDEF; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 208 "src/lexer.l"
{ g_last_ident_sym = NULL; return NATIVE; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 209 "src/lexer.l"
{ g_last_ident_sym = NULL; return RETURN; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 210 "src/lexer.l"
{ g_last_ident_sym = NULL; return IF; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 211 "src/lexer.l"
{ g_last_ident_sym = NULL; return ELSE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 212 "src/lexer.l"
{ g_last_ident_sym = NULL; return DO; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 213 "src/lexer.l"
{ g_last_ident_sym = NULL; return WHILE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 214 "src/lexer.l"
{ g_last_ident_sym = NULL; return FOR; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 215 "src/lexer.l"
{ g_last_ident_sym = NULL; return BREAK; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 216 "src/lexer.l"
{ g_last_ident_sym = NULL; return CONTINUE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 217 "src/lexer.l"
{ g_last_ident_sym = NULL; return GOTO; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 218 "src/lexer.l"
{ g_last_ident_sym = NULL; return ASM; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 219 "src/lexer.l"
{ g_last_ident_sym = NULL; return ASM; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 220 "src/lexer.l"
{ g_last_ident_sym = NULL; return ASM; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 221 "src/lexer.l"
{ g_last_ident_sym = NULL; return VOLATILE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 222 "src/lexer.l"
{ g_last_ident_sym = NULL; return VOLATILE; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 223 "src/lexer.l"
{ g_last_ident_sym = NULL; return SWITCH; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 224 "src/lexer.l"
{ g_last_ident_sym = NULL; return CASE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 225 "src/lexer.l"
{ g_last_ident_sym = NULL; return DEFAULT; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 226 "src/lexer.l"
{ g_last_ident_sym = NULL; return INT_KW; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 227 "src/lexer.l"
{ g_last_ident_sym = NULL; return FLOAT_KW; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 228 "src/lexer.l"
{ g_last_ident_sym = NULL; return VOID_KW; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 229 "src/lexer.l"
{ g_last_ident_sym = NULL; return BOOL_KW; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 230 "src/lexer.l"
{ g_last_ident_sym = NULL; return CHAR_KW; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 231 "src/lexer.l"
{ g_last_ident_sym = NULL; return NEW; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 232 "src/lexer.l"
{ g_last_ident_sym = NULL; return DELETE; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 233 "src/lexer.l"
{ g_last_ident_sym = NULL; return STATIC_CAST; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 234 "src/lexer.l"
{ g_last_ident_sym = NULL; return DYNAMIC_CAST; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 235 "src/lexer.l"
{ g_last_ident_sym = NULL; return CONST_CAST; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 236 "src/lexer.l"
{ g_last_ident_sym = NULL; return REINTERPRET_CAST; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 237 "src/lexer.l"
{ g_last_ident_sym = NULL; return THIS; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 238 "src/lexer.l"
{ g_last_ident_sym = NULL; return VIRTUAL; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 239 "src/lexer.l"
{ g_last_ident_sym = NULL; return CONST; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 240 "src/lexer.l"
{ g_last_ident_sym = NULL; return OPERATOR; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 241 "src/lexer.l"
{ g_last_ident_sym = NULL; return SIZEOF; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 242 "src/lexer.l"
{ g_last_ident_sym = NULL; return TRUE_KW; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 243 "src/lexer.l"
{ g_last_ident_sym = NULL; return FALSE_KW; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 244 "src/lexer.l"
{ g_last_ident_sym = NULL; return NULLPTR_KW; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 245 "src/lexer.l"
{ g_last_ident_sym = NULL; return FRIEND; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 247 "src/lexer.l"
{
    /* Arm (or clear) the qualifier context for the *next* token, using
     * whatever symbol the previous identifier-like token resolved to.
     * This must happen here, at scan time, not in a parser action --
     * see symtab_arm_qualifier's doc comment for why. */
    symtab_arm_qualifier(g_symtab, g_last_ident_sym);
    g_last_ident_sym = NULL;
    return COLONCOLON;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 257 "src/lexer.l"
{ g_last_ident_sym = NULL; return ARROW; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 258 "src/lexer.l"
{ g_last_ident_sym = NULL; return EQ; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 259 "src/lexer.l"
{ g_last_ident_sym = NULL; return NE; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 260 "src/lexer.l"
{ g_last_ident_sym = NULL; return LE; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 261 "src/lexer.l"
{ g_last_ident_sym = NULL; return GE; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 262 "src/lexer.l"
{ g_last_ident_sym = NULL; return ANDAND; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 263 "src/lexer.l"
{ g_last_ident_sym = NULL; return OROR; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 264 "src/lexer.l"
{ g_last_ident_sym = NULL; return PLUSEQ; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 265 "src/lexer.l"
{ g_last_ident_sym = NULL; return MINUSEQ; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 266 "src/lexer.l"
{ g_last_ident_sym = NULL; return STAREQ; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 267 "src/lexer.l"
{ g_last_ident_sym = NULL; return SLASHEQ; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 268 "src/lexer.l"
{ g_last_ident_sym = NULL; return INC; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 269 "src/lexer.l"
{ g_last_ident_sym = NULL; return DEC; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 270 "src/lexer.l"
{ g_last_ident_sym = NULL; return SHLEQ; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 271 "src/lexer.l"
{ g_last_ident_sym = NULL; return SHREQ; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 272 "src/lexer.l"
{ g_last_ident_sym = NULL; return SHL; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 273 "src/lexer.l"
{ g_last_ident_sym = NULL; return SHR; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 274 "src/lexer.l"
{ g_last_ident_sym = NULL; return ANDEQ; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 275 "src/lexer.l"
{ g_last_ident_sym = NULL; return OREQ; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 276 "src/lexer.l"
{ g_last_ident_sym = NULL; return XOREQ; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 278 "src/lexer.l"
{
    /* The core of the lexer hack: classify this identifier by consulting
     * the symbol table *right now*, using the qualifier context armed by
     * a preceding "::" if any (symtab_lookup_qualified consumes it).
     * Remember what we resolved in case the *next* token is "::". */
    yylval.str = strdup(yytext);
    Symbol *sym = symtab_lookup_qualified(g_symtab, yytext);
    g_last_ident_sym = sym;
    if (sym != NULL && (sym->kind == SYM_CLASS || sym->kind == SYM_TYPEDEF || sym->kind == SYM_ENUM || sym->kind == SYM_UNION)) {
        return TYPE_NAME;
    }
    return IDENTIFIER;
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 292 "src/lexer.l"
{
    /* Trailing f/F (real C++'s own "this is a float, not a double"
     * suffix) is matched and simply ignored -- atof() itself already
     * stops at the first character it can't parse, so `atof("3.9f")`
     * correctly yields 3.9 with no separate stripping needed. Harmless
     * either way in this project specifically: there is no distinct
     * "double" type here for the suffix to have disambiguated FROM --
     * every floating-point value is already `float` -- so the suffix
     * is accepted purely for compatibility with real C++ source that
     * writes it out of habit, not because it changes anything here. */
    g_last_ident_sym = NULL;
    yylval.fval = atof(yytext);
    return FLOAT_LITERAL;
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 307 "src/lexer.l"
{
    /* Hex literal -- 0x1F, 0XFF. strtol() with an explicit base of 16
     * already knows to accept (and skip over) a leading "0x"/"0X"
     * itself, so the full yytext, suffix included, can be handed to it
     * directly -- it stops parsing at the first character that doesn't
     * fit hex, i.e. exactly at the suffix, the same "already stops
     * where it needs to" reasoning the float-suffix rule above relies
     * on for atof(). */
    g_last_ident_sym = NULL;
    yylval.ival = (int)strtol(yytext, NULL, 16);
    return INT_LITERAL;
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 320 "src/lexer.l"
{
    /* Binary literal -- 0b1010, 0B11110000. NOT part of every C++
     * standard -- added in C++14; earlier standards have no binary-
     * literal syntax at all. Accepted here anyway as a convenience,
     * matching real C++14-and-later compilers, but worth knowing if
     * you're deliberately targeting something that predates that (see
     * the README/man page's own note on this). Unlike hex, strtol()
     * does NOT know to skip a "0b"/"0B" prefix itself even with an
     * explicit base of 2 (that leading-prefix convenience is specific
     * to base 16, and base 0's own auto-detection, per the C standard)
     * -- so the prefix is skipped explicitly here (yytext + 2) before
     * handing the rest to strtol(), which then stops at the suffix the
     * same way the hex/decimal rules do. */
    g_last_ident_sym = NULL;
    yylval.ival = (int)strtol(yytext + 2, NULL, 2);
    return INT_LITERAL;
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 338 "src/lexer.l"
{
    /* Octal literal -- 013 (=11 decimal), 0777. Real C++'s own
     * "leading zero means octal" rule -- listed BEFORE the plain
     * decimal rule below deliberately: flex's own longest-match-wins
     * only decides BETWEEN rules of different match length; for two
     * rules that would match the SAME text with the SAME length (e.g.
     * "013" matches both this rule and, if it came first, the decimal
     * one), flex breaks the tie by rule ORDER, first-listed wins -- so
     * this has to come first, or "013" would be silently (and
     * incorrectly) read as decimal 13 rather than octal 11. A leading
     * "0" whose next digit is 8 or 9 (invalid in octal, e.g. "089") is
     * NOT matched by this rule at all (requires at least one digit in
     * [0-7] after the leading 0) -- it falls through to the plain
     * decimal rule below instead, silently treating it as decimal 89,
     * not flagging real C++'s own "invalid digit in octal constant"
     * error. Matches this project's established best-effort philosophy
     * elsewhere -- not pedantically strict, but never silently wrong
     * about the COMMON case. strtol() with an explicit base of 8 treats
     * the whole matched text, leading 0 included, as ordinary base-8
     * digits -- no separate prefix-skipping needed, unlike binary
     * above. */
    g_last_ident_sym = NULL;
    yylval.ival = (int)strtol(yytext, NULL, 8);
    return INT_LITERAL;
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 364 "src/lexer.l"
{
    /* Suffix (u/U, l/L, and any combination -- ul, LL, ...) matched and
     * simply ignored, the exact same "atoi/atof/strtol already stops at
     * the first unparseable character" reasoning the float-literal
     * suffix rule above relies on. Deliberately permissive rather than
     * validating exactly which combinations real C++ allows (`lu` is
     * valid, `uu` is not, etc) -- this project has exactly one integer
     * type, so the suffix changes nothing regardless of which letters
     * appear or in what order; being permissive here costs nothing and
     * avoids rejecting otherwise-valid code over a distinction that
     * has no effect either way. */
    g_last_ident_sym = NULL;
    yylval.ival = atoi(yytext);
    return INT_LITERAL;
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 380 "src/lexer.l"
{
    /* SIMPLIFICATION: escape sequences inside the string are kept as
     * literal backslash-letter pairs rather than being decoded (\n stays
     * as the two characters '\' 'n'). Fine for a parsing skeleton; a real
     * codegen backend needs to decode these into the target C dialect's
     * own escape rules (and Vircon32 C's string/char handling should be
     * double-checked against its docs before assuming C escape parity). */
    g_last_ident_sym = NULL;
    size_t len = strlen(yytext);
    yylval.str = malloc(len - 1);
    memcpy(yylval.str, yytext + 1, len - 2);
    yylval.str[len - 2] = '\0';
    return STRING_LITERAL;
}
	YY_BREAK
case 86:
/* rule 86 can match eol */
YY_RULE_SETUP
#line 395 "src/lexer.l"
{
    g_last_ident_sym = NULL;
    if (yytext[1] == '\\') {
        switch (yytext[2]) {
            case 'n': yylval.ival = '\n'; break;
            case 't': yylval.ival = '\t'; break;
            case 'r': yylval.ival = '\r'; break;
            case '0': yylval.ival = '\0'; break;
            case '\\': yylval.ival = '\\'; break;
            case '\'': yylval.ival = '\''; break;
            case '"': yylval.ival = '"'; break;
            default: yylval.ival = yytext[2];
        }
    } else {
        yylval.ival = yytext[1];
    }
    return CHAR_LITERAL;
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 414 "src/lexer.l"
{
    /* Single-character tokens: operators/punctuation not covered above
     * ('+','-','*','/','%','<','>','=','!','&','|','~','(',')','{','}',
     * '[',']',';',',','.',':','?'). Returning the raw character code lets
     * parser.y reference them directly as e.g. '+' in grammar rules. */
    g_last_ident_sym = NULL;
    return yytext[0];
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 423 "src/lexer.l"
ECHO;
	YY_BREAK
#line 1779 "src/lexer.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 376 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 376 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 375);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 423 "src/lexer.l"


