#line 1 "src/lexer.c"

#line 3 "src/lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 75
#define YY_END_OF_BUFFER 76
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[310] =
    {   0,
        0,    0,   76,   74,    9,    8,   74,   74,   74,   74,
       74,   74,   74,   74,   71,   71,   74,   74,   74,   74,
       66,   74,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   74,    7,    9,   48,
        0,   72,    0,   51,   63,    0,    0,   55,   57,   53,
       58,   54,   46,    0,    1,   56,    0,   70,   71,    0,
       71,    0,   45,   61,   49,   47,   50,   62,   66,   65,
       66,   66,   66,   66,   66,   66,   66,   21,   66,   66,
       66,   66,   66,   66,   19,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,

       64,   52,    7,    7,    7,    7,   73,    0,    0,    1,
       67,   70,   69,   68,   59,   60,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   23,
       29,   66,   34,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,    7,    7,
        7,    7,    2,    0,   67,   69,   68,   32,   66,   27,
       33,   66,   66,   66,   66,   66,   66,   20,   12,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   40,   43,   66,   66,   31,   66,    7,    7,    7,
        7,    0,   67,   24,   10,   66,   66,   66,   66,   66,

       44,   30,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   22,    7,    7,    7,    7,   66,
       66,   66,   35,   66,   66,   66,   66,   66,   13,   66,
       18,   66,   11,   26,   66,   66,    7,    7,    7,    7,
       66,   66,   28,   66,   66,   66,   14,   66,   66,   66,
       17,   41,    7,    7,    7,    7,   66,   25,   66,   66,
       42,   66,   66,   66,    7,    7,    7,    7,   66,   66,
       16,   15,   66,   66,    7,    7,    7,    7,    5,    7,
       38,   66,   66,   66,    7,    7,    5,    6,   66,   66,
       36,    7,    4,    7,    7,    6,    6,   37,   66,    4,

        7,   66,    7,    3,   66,    3,   66,   39,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    1,    8,    9,    1,
        1,   10,   11,    1,   12,   13,   14,   15,   16,   17,
       17,   17,   17,   17,   17,   18,   18,   19,    1,   20,
       21,   22,    1,    1,   23,   24,   23,   23,   25,   26,
       27,   27,   27,   27,   27,   28,   27,   27,   27,   27,
       27,   27,   27,   27,   28,   27,   27,   29,   27,   27,
        1,   30,    1,   31,   32,    1,   33,   34,   35,   36,

       37,   38,   27,   39,   40,   27,   41,   42,   43,   44,
       45,   46,   27,   47,   48,   49,   50,   51,   52,   53,
       54,   27,    1,   55,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[56] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    4,    4,    4,    4,    1,    1,
        1,    1,    4,    4,    4,    4,    5,    5,    5,    1,
        1,    5,    4,    4,    4,    4,    4,    4,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    1
    } ;

static const flex_int16_t yy_base[328] =
    {   0,
        0,  620,  622,  656,   54,  656,  596,   51,   51,  582,
      586,   49,   52,   55,   69,   62,  583,   41,  576,   45,
        0,  566,   44,   63,   55,   57,   73,   50,   77,  535,
       21,  538,   64,   78,   81,  533,   74,   79,  129,  656,
       77,  656,    0,  656,  656,  562,  131,  656,  656,  656,
      656,  656,  656,  560,    0,  656,  120,  126,  132,  108,
      123,    0,  656,  548,  656,  656,  656,  547,    0,  656,
      522,  529,  517,  531,  530,  518,  114,    0,  517,  512,
      509,  516,  512,  509,    0,  506,  511,  501,  515,  113,
      517,  106,  124,  510,  507,  496,  499,  497,  503,  502,

      656,  656,    0,  496,  122,  499,  656,  525,  153,    0,
      162,  133,  169,  144,  656,  656,  492,  500,  484,  470,
      468,  121,  482,  477,  480,  475,  468,  462,  476,    0,
        0,  471,    0,  460,  455,  456,  462,  459,  452,  452,
      450,  450,  450,  460,  459,  446,  456,  449,  440,  436,
      439,  440,  656,  190,  656,  153,  162,    0,  445,    0,
        0,  433,  431,  439,  428,  417,  368,    0,    0,  370,
      357,  357,  371,  370,  365,  361,  351,  352,  358,  362,
      361,    0,    0,  359,  344,    0,  356,  348,  342,  348,
      341,  198,  205,    0,    0,  356,  343,  344,  348,  342,

        0,    0,  335,  331,  330,  343,  342,  339,  327,  335,
      320,  329,  319,  319,    0,  315,  300,  312,  308,  312,
      296,  296,    0,  309,  310,  297,  304,  291,    0,  292,
        0,  306,    0,    0,  299,  294,  333,  287,  331,  287,
      298,  293,    0,  295,  291,  278,    0,  287,  277,  287,
        0,    0,  243,  284,  187,  272,  267,    0,  279,  276,
        0,  265,  199,  209,  298,  239,  234,  237,  189,  204,
        0,    0,  199,  187,  190,  353,  408,  228,    0,  231,
        0,  184,  181,  180,  221,  463,    0,  224,  176,  186,
        0,  211,    0,  222,  518,  208,    0,    0,  174,    0,

      192,  158,  160,    0,  116,    0,   71,    0,  656,  573,
      578,  580,  585,  590,  595,   59,  600,  605,  610,  615,
      620,  625,  630,  635,  640,  645,  650
    } ;

static const flex_int16_t yy_def[328] =
    {   0,
      309,    1,  309,  309,  309,  309,  309,  310,  309,  311,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      312,  309,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  309,  313,  309,  309,
      310,  309,  310,  309,  309,  309,  311,  309,  309,  309,
      309,  309,  309,  314,  315,  309,  309,  309,  309,  309,
      309,  316,  309,  309,  309,  309,  309,  309,  312,  309,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,

      309,  309,  313,  313,  313,  313,  309,  314,  314,  315,
      309,  309,  309,  316,  309,  309,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  313,  313,
      313,  313,  309,  309,  309,  309,  309,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  313,  313,  313,
      313,  309,  309,  312,  312,  312,  312,  312,  312,  312,

      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  313,  313,  313,  313,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  313,  313,  313,  313,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  309,  313,  313,  313,  312,  312,  312,  312,
      312,  312,  312,  312,  317,  313,  318,  313,  312,  312,
      312,  312,  312,  312,  313,  317,  309,  318,  319,  320,
      312,  312,  312,  312,  321,  322,  319,  323,  312,  312,
      312,  321,  324,  313,  322,  323,  325,  312,  312,  324,

      326,  312,  326,  327,  312,  327,  312,  312,    0,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309
    } ;

static const flex_int16_t yy_nxt[712] =
    {   0,
        4,    5,    6,    5,    7,    8,    4,    9,   10,   11,
       12,   13,    4,   14,   15,   16,   16,   16,   17,   18,
       19,   20,   21,   21,   21,   21,   21,   21,   21,    4,
       22,   21,   21,   23,   24,   25,   26,   27,   21,   28,
       21,   21,   21,   29,   30,   31,   32,   33,   34,   21,
       35,   36,   21,   21,   37,   39,   42,   39,   44,   49,
       64,   65,  114,   51,   54,   67,   68,   90,   55,   50,
       91,   45,   52,   53,   57,   56,   59,   59,   59,   59,
       43,   57,   42,   58,   58,   58,   59,   85,   71,   61,
       72,   77,   60,   86,  101,   73,   61,   62,   80,   78,

       81,   74,   60,   61,   75,   82,   43,   76,   79,   87,
       61,   61,   93,   88,   83,   94,   95,   84,   61,  308,
       98,   62,  113,  113,   96,   99,  104,  105,  102,  106,
       39,   97,   39,  309,  111,  111,  111,  111,   57,   46,
       58,   58,   58,   59,   57,  138,   59,   59,   59,   59,
       61,  123,  135,  112,  139,  124,  140,  136,  150,   61,
      112,  151,  109,  307,   61,  304,  153,  112,  163,  164,
      141,  157,   61,   61,  112,  112,  111,  111,  111,  111,
      156,   61,  112,  113,  113,  157,  154,  155,  255,  157,
      305,  275,  267,  157,  156,  285,  156,  304,  154,  155,

      192,  192,  156,  157,  193,  193,  193,  193,  302,  297,
      156,  157,  193,  193,  193,  193,  293,  299,  156,  193,
      193,  193,  193,  294,  298,  297,  293,  301,  291,  290,
      155,  289,  280,  279,  284,  283,  282,  281,  280,  279,
      277,  274,  155,  103,  253,  273,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  265,  265,  265,  265,  265,
      265,  265,  103,  103,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  103,  103,  275,

      272,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      103,  103,  271,  270,  269,  268,  103,  103,  103,  103,
      266,  264,  263,  262,  261,  260,  259,  103,  103,  258,
      257,  256,  255,  254,  253,  252,  251,  250,  249,  248,
      247,  246,  245,  244,  243,  242,  241,  240,  239,  238,
      237,  236,  103,  103,  275,  235,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  103,  103,  234,  233,  232,
      231,  103,  103,  103,  103,  230,  229,  228,  227,  226,
      225,  224,  103,  103,  223,  222,  221,  220,  219,  218,
      217,  216,  215,  214,  213,  212,  211,  210,  209,  208,

      207,  206,  205,  204,  203,  202,  201,  103,  103,  277,
      200,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      286,  286,  286,  286,  286,  286,  286,  103,  103,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  103,  103,  294,  199,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  103,  103,  198,  197,  196,
      195,  103,  103,  103,  103,  194,  191,  190,  189,  188,
      187,  186,  103,  103,  185,  184,  183,  182,  181,  180,

      179,  178,  177,  176,  175,  174,  173,  172,  171,  170,
      169,  168,  167,  166,  165,  162,  161,  103,  103,  294,
      160,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      103,  103,  159,  158,  109,  152,  103,  103,  103,  103,
      149,  148,  147,  146,  145,  144,  143,  103,  103,  142,
      137,  134,  133,  132,  131,  130,  129,  128,  127,  126,
      125,  122,  121,  120,  119,  118,  117,  116,  115,  109,
      107,  100,  103,   41,   92,   41,   41,   41,   46,   46,
       89,   46,   46,   69,   69,  103,   70,  103,  103,  103,
      108,  108,  108,  108,  108,  110,   66,  110,  110,  110,

      276,   63,  276,  276,  276,  278,   48,  278,  278,  278,
      287,   47,  287,  287,  287,  288,   40,  288,  288,  288,
      292,  309,  292,  292,  292,  295,   38,  295,  295,  295,
      296,  309,  296,  296,  296,  300,  309,  300,  300,  300,
      297,  309,  297,  297,  297,  303,  309,  303,  303,  303,
      306,  309,  306,  306,  306,    3,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,

      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309
    } ;

static const flex_int16_t yy_chk[712] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    8,    5,    9,   12,
       18,   18,  316,   13,   14,   20,   20,   31,   14,   12,
       31,    9,   13,   13,   16,   14,   16,   16,   16,   16,
        8,   15,   41,   15,   15,   15,   15,   28,   23,   16,
       23,   25,   15,   28,   37,   24,   15,   15,   26,   25,

       26,   24,   15,   16,   24,   27,   41,   24,   25,   29,
       15,   16,   33,   29,   27,   33,   34,   27,   15,  307,
       35,   15,   60,   60,   34,   35,   38,   38,   37,   38,
       39,   34,   39,   47,   57,   57,   57,   57,   58,   47,
       58,   58,   58,   58,   59,   92,   59,   59,   59,   59,
       61,   77,   90,   58,   92,   77,   93,   90,  105,   59,
      112,  105,  109,  305,   61,  303,  109,   58,  122,  122,
       93,  114,   61,   59,  112,   58,  111,  111,  111,  111,
      156,   59,  112,  113,  113,  114,  111,  111,  255,  157,
      302,  275,  255,  114,  156,  275,  113,  301,  111,  111,

      154,  154,  156,  157,  154,  154,  154,  154,  299,  296,
      113,  157,  192,  192,  192,  192,  292,  290,  113,  193,
      193,  193,  193,  294,  289,  288,  285,  294,  284,  283,
      193,  282,  280,  278,  274,  273,  270,  269,  268,  267,
      266,  264,  193,  253,  253,  263,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  265,  265,

      262,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  260,  259,  257,  256,  265,  265,  265,  265,
      254,  250,  249,  248,  246,  245,  244,  265,  265,  242,
      241,  240,  239,  238,  237,  236,  235,  232,  230,  228,
      227,  226,  225,  224,  222,  221,  220,  219,  218,  217,
      216,  214,  265,  276,  276,  213,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  212,  211,  210,
      209,  276,  276,  276,  276,  208,  207,  206,  205,  204,
      203,  200,  276,  276,  199,  198,  197,  196,  191,  190,
      189,  188,  187,  185,  184,  181,  180,  179,  178,  177,

      176,  175,  174,  173,  172,  171,  170,  276,  277,  277,
      167,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  286,  286,  166,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  165,  164,  163,
      162,  286,  286,  286,  286,  159,  152,  151,  150,  149,
      148,  147,  286,  286,  146,  145,  144,  143,  142,  141,

      140,  139,  138,  137,  136,  135,  134,  132,  129,  128,
      127,  126,  125,  124,  123,  121,  120,  286,  295,  295,
      119,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  118,  117,  108,  106,  295,  295,  295,  295,
      104,  100,   99,   98,   97,   96,   95,  295,  295,   94,
       91,   89,   88,   87,   86,   84,   83,   82,   81,   80,
       79,   76,   75,   74,   73,   72,   71,   68,   64,   54,
       46,   36,  295,  310,   32,  310,  310,  310,  311,  311,
       30,  311,  311,  312,  312,  313,   22,  313,  313,  313,
      314,  314,  314,  314,  314,  315,   19,  315,  315,  315,

      317,   17,  317,  317,  317,  318,   11,  318,  318,  318,
      319,   10,  319,  319,  319,  320,    7,  320,  320,  320,
      321,    3,  321,  321,  321,  322,    2,  322,  322,  322,
      323,    0,  323,  323,  323,  324,    0,  324,  324,  324,
      325,    0,  325,  325,  325,  326,    0,  326,  326,  326,
      327,    0,  327,  327,  327,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,

      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/lexer.l"
#line 2 "src/lexer.l"
/*
 * lexer.l -- flex scanner.
 *
 * The interesting part is IDENTIFIER classification and the COLONCOLON
 * rule right below it: together they implement the "lexer hack" (deciding
 * TYPE_NAME vs IDENTIFIER by consulting the symbol table) plus qualified-
 * name (`v32::Timer`) support, entirely in scan order. See the long
 * comment on symtab_arm_qualifier() in symtab.h for *why* this lives here
 * and not in a parser reduction action.
 *
 * SIMPLIFICATION: no real preprocessor. Real C++ source needs macro
 * expansion and conditional compilation handled before this scanner ever
 * sees it -- neither happens here. As an interim measure, though, a line
 * starting with '#' is no longer silently discarded: it's captured
 * verbatim (see g_preprocessor_lines, driver.h) so codegen.c can re-emit
 * it at the top of the generated file, ahead of everything else. This
 * means a `#include "video.h"` a person actually wrote now survives the
 * round trip instead of having to be manually re-added by hand every
 * time -- but it is still just pass-through, not preprocessing: no
 * macro expansion, no #include resolution, no #ifdef evaluation, and a
 * captured #ifdef/#endif pair doesn't actually gate anything this
 * scanner sees, since it never interprets what was captured at all.
 *
 * ONE exception to "every `#`-line is just passed through unread": cart
 * hints (`#texture NAME "file.png"` / `#sound NAME "file.wav"`), a
 * targeted special-case recognized directly below, NOT the start of a
 * general preprocessor -- these two specific forms get parsed for their
 * NAME/filename and registered (see g_cart_textures/g_cart_sounds,
 * driver.h), instead of falling through to the generic pass-through
 * above. Modeled directly on v32lua's own `--#texture`/`--#sound` cart
 * hints. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "driver.h"
#include "parser.h"

/* Suppresses a warning in flex's OWN generated scanning machinery
 * (yy_get_next_buffer's buffer-resize check compares yy_size_t, an
 * unsigned type, against a plain int) -- not anything this project's
 * own code does; nothing here to fix on this project's side, since the
 * comparison lives entirely inside code flex itself emits below this
 * point, regenerated fresh from the flex skeleton every time and never
 * hand-edited. Confirmed present since the very first working build of
 * this project, mentioned in this file's own header comment as a known,
 * pre-existing, not-our-code issue from day one -- silencing it here
 * finally addresses the actual warning text directly, at the one place
 * that can, rather than continuing to just document it as expected in
 * every build report. No matching `#pragma ... pop` -- this generated
 * file is compiled standalone, never `#include`d elsewhere, so the
 * pragma's effect ending at end-of-file is exactly the intended scope. */
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wsign-compare"

/* Remembers the Symbol* (if any) resolved for the most recently scanned
 * IDENTIFIER/TYPE_NAME token, so that if the *next* token turns out to be
 * "::", we know what to arm the qualifier context with. Reset to NULL by
 * every other token so stale state can't leak across unrelated tokens
 * (e.g. "foo ; bar :: baz" must not treat foo as bar's qualifier). */
static Symbol *g_last_ident_sym = NULL;

#define YY_USER_ACTION \
    yylloc.first_line = yylloc.last_line = g_lex_lineno;

/* Appends one cart resource (a `#texture`/`#sound` hint) to `list`,
 * keeping id == list position exactly the way v32lua's own
 * cart_resource_append does (confirmed from its actual source) -- the
 * resource's id is never stored explicitly anywhere; it's always just
 * "whatever position this entry ends up at in the list," read back out
 * at both #define-emission time (codegen.c) and XML-emission time
 * (cartxml.c). */
static void register_cart_resource(CartResourceList *list, const char *name, const char *filename) {
    if (list->count == list->capacity) {
        list->capacity = list->capacity ? list->capacity * 2 : 8;
        list->items = realloc(list->items, sizeof(CartResource) * (size_t)list->capacity);
    }
    list->items[list->count].name = strdup(name);
    list->items[list->count].filename = strdup(filename);
    list->count++;
}
#line 790 "src/lexer.c"
#define YY_NO_INPUT 1
#line 792 "src/lexer.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 92 "src/lexer.l"


#line 1013 "src/lexer.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 310 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 656 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 94 "src/lexer.l"
{ /* line comment, discard */ }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 95 "src/lexer.l"
{ /* block comment, discard */ }
	YY_BREAK
/* Cart hints -- `#texture NAME "file.png"` / `#sound NAME "file.wav"`.
     * Matched BEFORE the generic "#"-line pass-through rule below,
     * deliberately: both would otherwise match the same full line (same
     * length), and flex's own "first rule wins on a length tie" behavior
     * means ORDER in this file is what actually decides which one a
     * cart hint gets recognized by -- these have to come first, or every
     * `#texture`/`#sound` line would just fall through to plain,
     * unrecognized pass-through instead. NAME is captured exactly as
     * written -- upper, lower, or mixed case, never forced to any
     * particular one. Does NOT also add the line to
     * g_preprocessor_lines -- a recognized cart hint is translated into
     * a `#define`, not passed through verbatim; only a genuinely
     * unrecognized `#`-line falls through to that. */
case 3:
YY_RULE_SETUP
#line 110 "src/lexer.l"
{
    char name[128] = {0};
    char filename[256] = {0};
    if (sscanf(yytext, "#texture %127s \"%255[^\"]\"", name, filename) == 2) {
        register_cart_resource(&g_cart_textures, name, filename);
    }
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 118 "src/lexer.l"
{
    char name[128] = {0};
    char filename[256] = {0};
    if (sscanf(yytext, "#sound %127s \"%255[^\"]\"", name, filename) == 2) {
        register_cart_resource(&g_cart_sounds, name, filename);
    }
}
	YY_BREAK
/* `#title "..."` / `#version ...` -- same "matched before the
     * generic pass-through, so it's recognized instead of just carried
     * through verbatim" reasoning as #texture/#sound above. title is
     * quoted (may contain spaces); version is a bare token (matching
     * v32lua's own "--#version 1.1", never quoted there either). Frees
     * any PREVIOUS value before overwriting -- a program with more than
     * one #title/#version simply keeps the last one seen, the same
     * "last write wins" behavior v32lua's own title/version hints have
     * (they just overwrite the same fixed-size buffer each time). */
case 5:
YY_RULE_SETUP
#line 135 "src/lexer.l"
{
    char title[256] = {0};
    if (sscanf(yytext, "#title \"%255[^\"]\"", title) == 1) {
        free(g_cart_title);
        g_cart_title = strdup(title);
    }
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 143 "src/lexer.l"
{
    char version[64] = {0};
    if (sscanf(yytext, "#version %63s", version) == 1) {
        free(g_cart_version);
        g_cart_version = strdup(version);
    }
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 151 "src/lexer.l"
{
    /* Preprocessor pass-through -- see this file's own header comment
     * and driver.h's PreprocessorLines for the full reasoning. Grows
     * g_preprocessor_lines by one and stores this line's text verbatim,
     * in original order; still returns no token, so the parser's own
     * grammar is completely unaffected by this -- codegen.c is the only
     * thing that ever reads this list. */
    if (g_preprocessor_lines.count == g_preprocessor_lines.capacity) {
        g_preprocessor_lines.capacity = g_preprocessor_lines.capacity ? g_preprocessor_lines.capacity * 2 : 8;
        g_preprocessor_lines.lines = realloc(g_preprocessor_lines.lines,
                                              sizeof(char *) * (size_t)g_preprocessor_lines.capacity);
    }
    g_preprocessor_lines.lines[g_preprocessor_lines.count++] = strdup(yytext);
}
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 166 "src/lexer.l"
{ g_lex_lineno++; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 167 "src/lexer.l"
{ /* whitespace */ }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 169 "src/lexer.l"
{ g_last_ident_sym = NULL; return CLASS; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 170 "src/lexer.l"
{ g_last_ident_sym = NULL; return STRUCT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 171 "src/lexer.l"
{ g_last_ident_sym = NULL; return ENUM; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 172 "src/lexer.l"
{ g_last_ident_sym = NULL; return PUBLIC; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 173 "src/lexer.l"
{ g_last_ident_sym = NULL; return PRIVATE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 174 "src/lexer.l"
{ g_last_ident_sym = NULL; return PROTECTED; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 175 "src/lexer.l"
{ g_last_ident_sym = NULL; return NAMESPACE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 176 "src/lexer.l"
{ g_last_ident_sym = NULL; return TYPEDEF; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 177 "src/lexer.l"
{ g_last_ident_sym = NULL; return RETURN; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 178 "src/lexer.l"
{ g_last_ident_sym = NULL; return IF; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 179 "src/lexer.l"
{ g_last_ident_sym = NULL; return ELSE; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 180 "src/lexer.l"
{ g_last_ident_sym = NULL; return DO; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 181 "src/lexer.l"
{ g_last_ident_sym = NULL; return WHILE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 182 "src/lexer.l"
{ g_last_ident_sym = NULL; return FOR; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 183 "src/lexer.l"
{ g_last_ident_sym = NULL; return BREAK; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 184 "src/lexer.l"
{ g_last_ident_sym = NULL; return CONTINUE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 185 "src/lexer.l"
{ g_last_ident_sym = NULL; return SWITCH; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 186 "src/lexer.l"
{ g_last_ident_sym = NULL; return CASE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 187 "src/lexer.l"
{ g_last_ident_sym = NULL; return DEFAULT; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 188 "src/lexer.l"
{ g_last_ident_sym = NULL; return INT_KW; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 189 "src/lexer.l"
{ g_last_ident_sym = NULL; return FLOAT_KW; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 190 "src/lexer.l"
{ g_last_ident_sym = NULL; return VOID_KW; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 191 "src/lexer.l"
{ g_last_ident_sym = NULL; return BOOL_KW; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 192 "src/lexer.l"
{ g_last_ident_sym = NULL; return CHAR_KW; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 193 "src/lexer.l"
{ g_last_ident_sym = NULL; return NEW; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 194 "src/lexer.l"
{ g_last_ident_sym = NULL; return DELETE; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 195 "src/lexer.l"
{ g_last_ident_sym = NULL; return STATIC_CAST; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 196 "src/lexer.l"
{ g_last_ident_sym = NULL; return DYNAMIC_CAST; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 197 "src/lexer.l"
{ g_last_ident_sym = NULL; return CONST_CAST; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 198 "src/lexer.l"
{ g_last_ident_sym = NULL; return REINTERPRET_CAST; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 199 "src/lexer.l"
{ g_last_ident_sym = NULL; return THIS; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 200 "src/lexer.l"
{ g_last_ident_sym = NULL; return VIRTUAL; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 201 "src/lexer.l"
{ g_last_ident_sym = NULL; return OPERATOR; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 202 "src/lexer.l"
{ g_last_ident_sym = NULL; return TRUE_KW; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 203 "src/lexer.l"
{ g_last_ident_sym = NULL; return FALSE_KW; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 205 "src/lexer.l"
{
    /* Arm (or clear) the qualifier context for the *next* token, using
     * whatever symbol the previous identifier-like token resolved to.
     * This must happen here, at scan time, not in a parser action --
     * see symtab_arm_qualifier's doc comment for why. */
    symtab_arm_qualifier(g_symtab, g_last_ident_sym);
    g_last_ident_sym = NULL;
    return COLONCOLON;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 215 "src/lexer.l"
{ g_last_ident_sym = NULL; return ARROW; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 216 "src/lexer.l"
{ g_last_ident_sym = NULL; return EQ; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 217 "src/lexer.l"
{ g_last_ident_sym = NULL; return NE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 218 "src/lexer.l"
{ g_last_ident_sym = NULL; return LE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 219 "src/lexer.l"
{ g_last_ident_sym = NULL; return GE; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 220 "src/lexer.l"
{ g_last_ident_sym = NULL; return ANDAND; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 221 "src/lexer.l"
{ g_last_ident_sym = NULL; return OROR; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 222 "src/lexer.l"
{ g_last_ident_sym = NULL; return PLUSEQ; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 223 "src/lexer.l"
{ g_last_ident_sym = NULL; return MINUSEQ; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 224 "src/lexer.l"
{ g_last_ident_sym = NULL; return STAREQ; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 225 "src/lexer.l"
{ g_last_ident_sym = NULL; return SLASHEQ; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 226 "src/lexer.l"
{ g_last_ident_sym = NULL; return INC; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 227 "src/lexer.l"
{ g_last_ident_sym = NULL; return DEC; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 228 "src/lexer.l"
{ g_last_ident_sym = NULL; return SHLEQ; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 229 "src/lexer.l"
{ g_last_ident_sym = NULL; return SHREQ; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 230 "src/lexer.l"
{ g_last_ident_sym = NULL; return SHL; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 231 "src/lexer.l"
{ g_last_ident_sym = NULL; return SHR; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 232 "src/lexer.l"
{ g_last_ident_sym = NULL; return ANDEQ; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 233 "src/lexer.l"
{ g_last_ident_sym = NULL; return OREQ; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 234 "src/lexer.l"
{ g_last_ident_sym = NULL; return XOREQ; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 236 "src/lexer.l"
{
    /* The core of the lexer hack: classify this identifier by consulting
     * the symbol table *right now*, using the qualifier context armed by
     * a preceding "::" if any (symtab_lookup_qualified consumes it).
     * Remember what we resolved in case the *next* token is "::". */
    yylval.str = strdup(yytext);
    Symbol *sym = symtab_lookup_qualified(g_symtab, yytext);
    g_last_ident_sym = sym;
    if (sym != NULL && (sym->kind == SYM_CLASS || sym->kind == SYM_TYPEDEF || sym->kind == SYM_ENUM)) {
        return TYPE_NAME;
    }
    return IDENTIFIER;
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 250 "src/lexer.l"
{
    /* Trailing f/F (real C++'s own "this is a float, not a double"
     * suffix) is matched and simply ignored -- atof() itself already
     * stops at the first character it can't parse, so `atof("3.9f")`
     * correctly yields 3.9 with no separate stripping needed. Harmless
     * either way in this project specifically: there is no distinct
     * "double" type here for the suffix to have disambiguated FROM --
     * every floating-point value is already `float` -- so the suffix
     * is accepted purely for compatibility with real C++ source that
     * writes it out of habit, not because it changes anything here. */
    g_last_ident_sym = NULL;
    yylval.fval = atof(yytext);
    return FLOAT_LITERAL;
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 265 "src/lexer.l"
{
    /* Hex literal -- 0x1F, 0XFF. strtol() with an explicit base of 16
     * already knows to accept (and skip over) a leading "0x"/"0X"
     * itself, so the full yytext, suffix included, can be handed to it
     * directly -- it stops parsing at the first character that doesn't
     * fit hex, i.e. exactly at the suffix, the same "already stops
     * where it needs to" reasoning the float-suffix rule above relies
     * on for atof(). */
    g_last_ident_sym = NULL;
    yylval.ival = (int)strtol(yytext, NULL, 16);
    return INT_LITERAL;
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 278 "src/lexer.l"
{
    /* Binary literal -- 0b1010, 0B11110000. NOT part of every C++
     * standard -- added in C++14; earlier standards have no binary-
     * literal syntax at all. Accepted here anyway as a convenience,
     * matching real C++14-and-later compilers, but worth knowing if
     * you're deliberately targeting something that predates that (see
     * the README/man page's own note on this). Unlike hex, strtol()
     * does NOT know to skip a "0b"/"0B" prefix itself even with an
     * explicit base of 2 (that leading-prefix convenience is specific
     * to base 16, and base 0's own auto-detection, per the C standard)
     * -- so the prefix is skipped explicitly here (yytext + 2) before
     * handing the rest to strtol(), which then stops at the suffix the
     * same way the hex/decimal rules do. */
    g_last_ident_sym = NULL;
    yylval.ival = (int)strtol(yytext + 2, NULL, 2);
    return INT_LITERAL;
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 296 "src/lexer.l"
{
    /* Octal literal -- 013 (=11 decimal), 0777. Real C++'s own
     * "leading zero means octal" rule -- listed BEFORE the plain
     * decimal rule below deliberately: flex's own longest-match-wins
     * only decides BETWEEN rules of different match length; for two
     * rules that would match the SAME text with the SAME length (e.g.
     * "013" matches both this rule and, if it came first, the decimal
     * one), flex breaks the tie by rule ORDER, first-listed wins -- so
     * this has to come first, or "013" would be silently (and
     * incorrectly) read as decimal 13 rather than octal 11. A leading
     * "0" whose next digit is 8 or 9 (invalid in octal, e.g. "089") is
     * NOT matched by this rule at all (requires at least one digit in
     * [0-7] after the leading 0) -- it falls through to the plain
     * decimal rule below instead, silently treating it as decimal 89,
     * not flagging real C++'s own "invalid digit in octal constant"
     * error. Matches this project's established best-effort philosophy
     * elsewhere -- not pedantically strict, but never silently wrong
     * about the COMMON case. strtol() with an explicit base of 8 treats
     * the whole matched text, leading 0 included, as ordinary base-8
     * digits -- no separate prefix-skipping needed, unlike binary
     * above. */
    g_last_ident_sym = NULL;
    yylval.ival = (int)strtol(yytext, NULL, 8);
    return INT_LITERAL;
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 322 "src/lexer.l"
{
    /* Suffix (u/U, l/L, and any combination -- ul, LL, ...) matched and
     * simply ignored, the exact same "atoi/atof/strtol already stops at
     * the first unparseable character" reasoning the float-literal
     * suffix rule above relies on. Deliberately permissive rather than
     * validating exactly which combinations real C++ allows (`lu` is
     * valid, `uu` is not, etc) -- this project has exactly one integer
     * type, so the suffix changes nothing regardless of which letters
     * appear or in what order; being permissive here costs nothing and
     * avoids rejecting otherwise-valid code over a distinction that
     * has no effect either way. */
    g_last_ident_sym = NULL;
    yylval.ival = atoi(yytext);
    return INT_LITERAL;
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 338 "src/lexer.l"
{
    /* SIMPLIFICATION: escape sequences inside the string are kept as
     * literal backslash-letter pairs rather than being decoded (\n stays
     * as the two characters '\' 'n'). Fine for a parsing skeleton; a real
     * codegen backend needs to decode these into the target C dialect's
     * own escape rules (and Vircon32 C's string/char handling should be
     * double-checked against its docs before assuming C escape parity). */
    g_last_ident_sym = NULL;
    size_t len = strlen(yytext);
    yylval.str = malloc(len - 1);
    memcpy(yylval.str, yytext + 1, len - 2);
    yylval.str[len - 2] = '\0';
    return STRING_LITERAL;
}
	YY_BREAK
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 353 "src/lexer.l"
{
    g_last_ident_sym = NULL;
    if (yytext[1] == '\\') {
        switch (yytext[2]) {
            case 'n': yylval.ival = '\n'; break;
            case 't': yylval.ival = '\t'; break;
            case 'r': yylval.ival = '\r'; break;
            case '0': yylval.ival = '\0'; break;
            case '\\': yylval.ival = '\\'; break;
            case '\'': yylval.ival = '\''; break;
            case '"': yylval.ival = '"'; break;
            default: yylval.ival = yytext[2];
        }
    } else {
        yylval.ival = yytext[1];
    }
    return CHAR_LITERAL;
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 372 "src/lexer.l"
{
    /* Single-character tokens: operators/punctuation not covered above
     * ('+','-','*','/','%','<','>','=','!','&','|','~','(',')','{','}',
     * '[',']',';',',','.',':','?'). Returning the raw character code lets
     * parser.y reference them directly as e.g. '+' in grammar rules. */
    g_last_ident_sym = NULL;
    return yytext[0];
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 381 "src/lexer.l"
ECHO;
	YY_BREAK
#line 1643 "src/lexer.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 310 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 310 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 309);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 381 "src/lexer.l"


