#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <getopt.h>
#include <unistd.h> /* access() */
#include "driver.h"
#include "parser.h"
#include "sema.h"
#include "lower.h"
#include "codegen.h"
#include "v32cxx.h"
#include "config.h"
#include "pathutil.h"
#include "cartxml.h"
#include "debugmap.h"
#include "prescan.h"
#include "compat.h"
#include "generic.h"

#define  MAX_INCLUDE_DIRS V32CXX_MAX_INCLUDE_DIRS

/* Definitions for the globals declared extern in driver.h. */
SymTab *g_symtab = NULL;
AstNode *g_program = NULL;
Symbol *g_current_class_sym = NULL;
int g_lex_lineno = 1;
int g_parse_errors = 0;
const char *g_current_filename = "<stdin>";
PreprocessorLines g_preprocessor_lines = {NULL, 0, 0};
int g_uses_new_or_delete = 0;
CodegenTarget g_target = TARGET_VIRCON32;
int g_reject_bit_fields = 0;   /* --reject-bit-fields */
CartResourceList g_cart_textures = {NULL, 0, 0};
CartResourceList g_cart_sounds = {NULL, 0, 0};
char *g_cart_title = NULL;
char *g_cart_version = NULL;

extern FILE *yyin;

static void print_usage(const char *prog_name) {
    fprintf(stderr, "usage: %s [-o output.c] [-c] [-v[v[v]]] [-I dir] [-D name[=value]] [-U name] [-x] [-b] [-g] [--target=vircon32|standard] [--reject-bit-fields] [--no-inline-containers] [--version] <input.cpp>\n", prog_name);
    fprintf(stderr, "  -o output.c   write generated Vircon32 C to this file (default:\n"
                     "                <input> with its extension replaced by .c)\n");
    fprintf(stderr,  "  --no-inline-containers\n"
                     "                keep std::array/std::vector accessors (v[i],\n"
                     "                v.size(), ...) as function calls instead of\n"
                     "                writing them in place\n");
    fprintf(stderr,  "  -c            transpile without requiring a `main` to exist --\n"
                     "                like a real compiler's -c (\"compile only\"), for a\n"
                     "                library/module fragment rather than a complete,\n"
                     "                standalone-compilable program\n");
    fprintf(stderr,  "  -v            verbose: print progress as each stage runs.\n"
                     "                Stackable -- -vv also sprinkles explanatory\n"
                     "                comments into the generated .c itself, at\n"
                     "                vtables/this/new/delete/destructor-at-scope-exit\n"
                     "                and other non-obvious points; -vvv additionally\n"
                     "                prints the AST/semantic-analysis/lowering dumps.\n"
                     "                Silent by default (no -v at all).\n");
    fprintf(stderr,  "  -I <dir>, --include=<dir>\n                add <dir> to the #include search path. Only\n"
                     "                .hpp/.cpp includes are resolved by v32c++\n"
                     "                (.h and system includes pass through to the\n"
                     "                generated C unchanged). May be repeated.\n"
                     "                Searched after -I: $" V32CXX_INCLUDE_ENV_VAR " (colon-\n"
                     "                separated), then " V32CXX_INCLUDE_PATH "\n");
    fprintf(stderr,  "  -D name[=value]\n"
                     "                define a macro, as if `#define name value` (value\n"
                     "                defaults to 1) began the source. May be repeated.\n"
                     "  -U name       undefine a macro (one from an earlier -D)\n");
    fprintf(stderr,  "  -x, --no-xml  don't generate the Vircon32 cart-packing XML file\n"
                     "                alongside the generated C (generated by default\n"
                     "                whenever a .c file is actually written; never\n"
                     "                generated at all for --target=standard, with or\n"
                     "                without this flag)\n");
    fprintf(stderr,  "  -b            transpile a Vircon32 BIOS, not an ordinary cartridge:\n"
                     "                the generated XML's <rom> gets type=\"bios\"; requires\n"
                     "                exactly one #texture, at most one #sound, and a\n"
                     "                `void error_handler()` function in addition to `main`\n");
    fprintf(stderr,  "  -g            also write <output>.debug, a C-line <-> C++-line\n"
                     "                mapping alongside the generated C\n");
    fprintf(stderr,  "  --target=X    output C dialect: \"vircon32\" (or \"v32\", the default)\n"
                     "                for the real Vircon32 compiler's own quirks, or\n"
                     "                \"standard\" (or \"std\") for plain, portable C --\n"
                     "                no cart-packing XML or debug map either way for\n"
                     "                --target=standard, since both are Vircon32-\n"
                     "                platform concerns with no meaning outside it. See\n"
                     "                docs/VIRCON32_QUIRKS.md for the itemized list of\n"
                     "                what this actually changes.\n");
    fprintf(stderr,  "  --version     print version information and exit\n");
}

/* Builds the system include list searched after every -I dir (and, for
 * quote form, the current directory): each non-empty entry of the
 * colon-separated $V32CXX_INCLUDE in order, then V32CXX_INCLUDE_PATH.
 * See config.h. Entries are strdup'd and live for the whole run (freed
 * by the OS at exit, the same single-shot trade made elsewhere). Returns
 * the count stored in `dirs`, or -1 when `max` is exceeded. */
static int build_system_include_dirs(char **dirs, int max) {
    int n = 0;
    const char *env = getenv(V32CXX_INCLUDE_ENV_VAR);
    if (env != NULL) {
        const char *p = env;
        while (*p) {
            const char *colon = strchr(p, COMPAT_PATH_LIST_SEP);
            size_t len = colon ? (size_t)(colon - p) : strlen(p);
            if (len > 0) {
                if (n >= max) return -1;
                char *dir = malloc(len + 1);
                memcpy(dir, p, len);
                dir[len] = '\0';
                dirs[n++] = dir;
            }
            if (colon == NULL) break;
            p = colon + 1;
        }
    }
    if (V32CXX_INCLUDE_PATH[0] != '\0') {
        if (n >= max) return -1;
        dirs[n++] = strdup(V32CXX_INCLUDE_PATH);
    }
    return n;
}

/* Appends each non-empty entry of a colon-separated list. Returns the new
 * count, or -1 past `max`. */
static int add_path_list(char **dirs, int n, int max, const char *list) {
    const char *p = list;
    while (p != NULL && *p) {
        const char *colon = strchr(p, COMPAT_PATH_LIST_SEP);
        size_t len = colon ? (size_t)(colon - p) : strlen(p);
        if (len > 0) {
            if (n >= max) return -1;
            char *dir = malloc(len + 1);
            memcpy(dir, p, len);
            dir[len] = '\0';
            dirs[n++] = dir;
        }
        if (colon == NULL) break;
        p = colon + 1;
    }
    return n;
}

/* The SDK include directories (see config.h): $V32CXX_SDK_INCLUDE, then the
 * include/ folder beside the Vircon32 `compile` on $PATH (recognized by
 * holding video.h, so an unrelated `compile` is ignored), then
 * V32CXX_SDK_INCLUDE_PATH. Returns the count, or -1 past `max`. */
static int build_sdk_include_dirs(char **dirs, int max) {
    int n = add_path_list(dirs, 0, max, getenv(V32CXX_SDK_INCLUDE_ENV_VAR));
    if (n < 0) return -1;
    const char *path = getenv("PATH");
    for (const char *p = path; p != NULL && *p; ) {
        const char *colon = strchr(p, COMPAT_PATH_LIST_SEP);
        size_t len = colon ? (size_t)(colon - p) : strlen(p);
        if (len > 0) {
            char *exe = malloc(len + strlen(V32CXX_SDK_COMPILER_NAME) + 2);
            char *inc = malloc(len + 32);
            sprintf(exe, "%.*s/%s", (int)len, p, V32CXX_SDK_COMPILER_NAME);
            sprintf(inc, "%.*s/include", (int)len, p);
            char *probe = malloc(strlen(inc) + 16);
            sprintf(probe, "%s/video.h", inc);
            int ok = compat_is_executable(exe) && access(probe, R_OK) == 0;
            free(exe);
            free(probe);
            if (ok) {
                if (n >= max) { free(inc); return -1; }
                dirs[n++] = inc;
                break;                 /* the first one on $PATH, as the shell would run */
            }
            free(inc);
        }
        if (colon == NULL) break;
        p = colon + 1;
    }
    if (V32CXX_SDK_INCLUDE_PATH[0] != '\0') {
        if (n >= max) return -1;
        dirs[n++] = strdup(V32CXX_SDK_INCLUDE_PATH);
    }
    return n;
}

static void print_version(void) {
    /* Matches v32lua's own --version format exactly, for consistency
     * between the two sibling projects -- see v32cxx.h for VERSION/
     * AUTHOR/URL themselves. */
    printf("v32c++ %s\n", VERSION);
    printf("C++ Transpiler for Vircon32 (v32c++) by %s\n", AUTHOR);
    printf("  github: %s\n", URL);
}

/* Checks the three constraints -b (BIOS transpilation) imposes, none of
 * which sema_run() itself knows or cares about -- same "CLI-level
 * default, not a language rule" framing as require_main above. Reports
 * EVERY violation found, not just the first -- these are three
 * independent constraints, so stopping at the first one just means the
 * person re-runs to discover the second, then the third, one at a time
 * for no real reason. Returns 1 if all three hold, 0 otherwise. Call
 * only after sema_run() has completed with zero errors, same rule as
 * sema_program_has_main/sema_program_has_function -- and after
 * g_cart_textures/g_cart_sounds are fully populated, which lexing
 * already guarantees by the time this runs. */
static int validate_bios_constraints(const AstNode *program, const char *filename) {
    int ok = 1;
    if (g_cart_textures.count != 1) {
        fprintf(stderr, "---- error: -b requires exactly one #texture in %s (found %d) ----\n",
                filename, g_cart_textures.count);
        ok = 0;
    }
    if (g_cart_sounds.count > 1) {
        fprintf(stderr, "---- error: -b allows at most one #sound in %s (found %d) ----\n",
                filename, g_cart_sounds.count);
        ok = 0;
    }
    if (!sema_program_has_function(program, "error_handler")) {
        fprintf(stderr, "---- error: -b requires a 'void error_handler()' function in %s ----\n",
                filename);
        ok = 0;
    }
    return ok;
}

int  main (int  argc, char **argv)
{
    char       *include_dirs[MAX_INCLUDE_DIRS];
    const char *output_filename    = NULL;
    int         require_main       = 1;
    int         verbosity          = 0;
    int         emit_xml           = 1;
    int         is_bios            = 0;
    int         emit_debug         = 0;
    int         opt                = 0;
    int         include_dir_count  = 0;

    static struct option long_options[] = {
        { "version", no_argument,       0, 'V' },
        { "no-xml",  no_argument,       0, 'x' },
        { "include", required_argument, 0, 'I' },
        { "target",  required_argument, 0, 'T' },
        { "reject-bit-fields", no_argument, 0, 'B' },
        { "no-inline-containers", no_argument, 0, 'N' },
        { 0,         0,                 0, 0   }
    };

    while ((opt = getopt_long(argc, argv, "o:cvxbgI:D:U:", long_options, NULL)) != -1) {
        switch (opt) {
            case 'o':
                output_filename = optarg;
                break;
            case 'c':
                require_main = 0;
                break;
            case 'v':
                /* Stackable -- getopt_long's own short-option bundling
                 * already turns "-vvv" into three separate 'v' cases
                 * here, one per repetition, same as it would for
                 * "-v -v -v"; nothing extra needed to support either
                 * spelling. */
                verbosity++;
                break;
            case 'I':
                /* -I <dir> -- the include search path for angle-form
                 * .hpp includes, and the fallback order for quote-form
                 * ones; see prescan.h. Multiple -I flags keep their
                 * command-line order, matching every real compiler. */
                if (include_dir_count < MAX_INCLUDE_DIRS) {
                    include_dirs[include_dir_count++] = optarg;
                } else {
                    fprintf(stderr, "---- error: too many -I directories (max %d) ----\n",
                            MAX_INCLUDE_DIRS);
                    return 1;
                }
                break;
            case 'D':
                /* -D NAME / -D NAME=VALUE: as if `#define NAME VALUE`
                 * (VALUE defaults to 1) opened the source; it reaches the
                 * generated C like any other #define. -U NAME undoes an
                 * earlier -D. Applied in command-line order. */
                prescan_add_cmdline_macro(optarg, 0);
                break;
            case 'U':
                prescan_add_cmdline_macro(optarg, 1);
                break;
            case 'x':
                emit_xml = 0;
                break;
            case 'b':
                is_bios = 1;
                break;
            case 'g':
                emit_debug = 1;
                break;
            case 'T':
                /* "vircon32"/"v32" (the default, so this flag only
                 * needs to be passed to ask for the OTHER dialect) or
                 * "standard"/"std" -- see driver.h's own CodegenTarget
                 * doc comment and docs/VIRCON32_QUIRKS.md for what
                 * this actually changes. Case-sensitive, matching
                 * every other value this CLI takes (filenames,
                 * for instance) -- no reason to special-case this one
                 * flag's own matching to be more lenient than the rest
                 * of the tool already is. */
                if (strcmp(optarg, "vircon32") == 0 || strcmp(optarg, "v32") == 0) {
                    g_target = TARGET_VIRCON32;
                } else if (strcmp(optarg, "standard") == 0 || strcmp(optarg, "std") == 0) {
                    g_target = TARGET_STANDARD;
                } else {
                    fprintf(stderr, "---- error: unrecognized --target value '%s' "
                                     "(expected vircon32, v32, standard, or std) ----\n", optarg);
                    return 1;
                }
                break;
            case 'B':
                /* --reject-bit-fields: a bit-field is a hard error
                 * instead of a warning plus a full-word member. */
                g_reject_bit_fields = 1;
                break;
            case 'N':
                /* --no-inline-containers: std::array/std::vector accessors
                 * (v[i], v.size(), ...) stay real function calls instead
                 * of being written in place -- for reading the generated
                 * C next to the class it came from, or for comparing. */
                g_no_inline_containers = 1;
                break;
            case 'V':
                print_version();
                return 0;
            default:
                print_usage(argv[0]);
                return 1;
        }
    }

    if (g_target == TARGET_STANDARD) {
        /* Cart-packing XML and the debug map are both Vircon32-
         * PLATFORM concerns (cart metadata, a mapping meant for
         * Vircon32's own debugger) with no meaning outside it at all
         * -- forced off here, a single point of truth, rather than
         * threading a second "and g_target == TARGET_VIRCON32" check
         * into each of the two call sites below and risking one of
         * them drifting out of sync with the other later. Neither
         * -x/--no-xml nor -g needs to be passed for this: asking for
         * standard-C output already implies neither Vircon32-specific
         * output exists to opt into, the same way asking for a BIOS
         * cartridge (-b) implies constraints of its own without
         * needing a person to separately configure each one by hand. */
        emit_xml = 0;
        emit_debug = 0;
    }

    if (optind >= argc) {
        print_usage(argv[0]);
        return 1;
    }

    const char *input_filename = argv[optind];
    /* Include pre-scan FIRST: .hpp/.cpp #includes are expanded into a
     * monolithic temp stream here (with line markers to keep the
     * lexer's file/line tracking honest), and .h/system includes are
     * left in place for lexer.l's existing verbatim pass-through.
     * tmpfile() unlinks on fclose, so `yyin`'s cleanup is just the
     * fclose(yyin) this CLI already does at exit-equivalent points.
     * See prescan.h for the full reasoning. */
    char *system_dirs[MAX_INCLUDE_DIRS];
    int system_dir_count = build_system_include_dirs(system_dirs, MAX_INCLUDE_DIRS - include_dir_count);
    if (system_dir_count < 0) {
        fprintf(stderr, "---- error: too many include directories (-I plus $%s, max %d) ----\n",
                V32CXX_INCLUDE_ENV_VAR, MAX_INCLUDE_DIRS);
        return 1;
    }
    char *sdk_dirs[MAX_INCLUDE_DIRS];
    int sdk_dir_count = build_sdk_include_dirs(sdk_dirs, MAX_INCLUDE_DIRS);
    if (sdk_dir_count < 0) {
        fprintf(stderr, "---- error: too many SDK include directories ($%s, max %d) ----\n",
                V32CXX_SDK_INCLUDE_ENV_VAR, MAX_INCLUDE_DIRS);
        return 1;
    }
    if (verbosity >= 1)
        for (int i = 0; i < sdk_dir_count; i++)
            printf("SDK header search: %s\n", sdk_dirs[i]);
    prescan_set_sdk_dirs(sdk_dirs, sdk_dir_count);
    FILE *f = prescan_expand(input_filename, include_dirs, include_dir_count,
                             system_dirs, system_dir_count);
    if (f == NULL) {
        return 1; /* message already printed, with file/line context */
    }
    yyin = f;
    g_current_filename = input_filename;

    if (verbosity >= 3) {
        /* Dump the post-prescan stream EXACTLY as the lexer will see it.
         * Rewind afterwards -- yyparse() must read from the start. */
        printf("---- post-prescan expanded source (as fed to the lexer) ----\n");
        int c, dump_lineno = 1, bol = 1;
        while ((c = fgetc(yyin)) != EOF) {
            if (bol) { printf("%5d: ", dump_lineno); bol = 0; }
            putchar(c);
            if (c == '\n') { dump_lineno++; bol = 1; }
        }
        rewind(yyin);
        printf("---- end expanded source ----\n");
    }

    char *derived_output = NULL;
    if (output_filename == NULL) {
        /* Same default the real Vircon32 C compiler and v32lua both
         * use: the input's own extension, replaced with ".c". */
        derived_output = replace_extension(input_filename, ".c");
        output_filename = derived_output;
    }

    g_symtab = symtab_create();

    if (verbosity >= 1) printf("stage 1: running lexer/parser\n");
    int rc = yyparse();
    if (rc == 0 && g_parse_errors > 0) rc = 1; /* messages already printed */

    /* std::array<T, N> classes the program named: generated, parsed and
     * spliced in before anything else looks at the AST (generic.h). */
    if (rc == 0 && g_program != NULL && generic_instantiate_pending() != 0) rc = 1;

    /* `Enemy(1, 2, 3)` as an expression: each becomes a named local
     * before anything else looks at the AST (ast.c). */
    if (rc == 0 && g_program != NULL && desugar_unnamed_objects(&g_program->list) != 0) rc = 1;

    if (rc == 0 && g_program != NULL) {
        /* C storage classes, resolved before anything else looks at the
         * tree: static locals become file-scope variables, and repeated
         * file-scope declarations of one variable (extern + definition)
         * become one. */
        hoist_static_locals(&g_program->list);
        merge_tentative_globals(&g_program->list);
        /* implicit default constructors / destructors, written into the
         * classes that need one -- see ast.c */
        apply_default_member_initializers(&g_program->list);
        synthesize_implicit_members(&g_program->list);

        if (verbosity >= 3) {
            printf("---- parse OK: AST for %s ----\n", g_current_filename);
            ast_dump(g_program, 0);
        }

        if (verbosity >= 1) printf("stage 2: running semantic analyzer\n");
        int sema_errors = sema_run(g_program);
        if (verbosity >= 3) sema_dump(g_program);
        int sema_warnings = sema_get_warning_count();
        if (sema_warnings > 0) {
            /* Printed unconditionally whenever nonzero -- independent of
             * the error/success branching just below, since a warning
             * (currently: a user-written `dynamic_cast`, see
             * sema_get_warning_count's own doc comment in sema.h) never
             * itself causes this transpile to fail, so it still deserves
             * visibility even on an otherwise-clean, successful run. */
            fprintf(stderr, "---- %d warning(s) in %s ----\n", sema_warnings, g_current_filename);
        }
        if (sema_errors > 0) {
            fprintf(stderr, "---- %d semantic error(s) in %s ----\n", sema_errors, g_current_filename);
            rc = 1;
        } else if (require_main && !sema_program_has_main(g_program)) {
            /* main.c's own CLI-level default, entirely separate from
             * anything sema_run() itself checks -- this project's
             * compiler has never required a `main` to exist to
             * transpile something correctly, and still doesn't; `-c`
             * (like a real compiler's "compile only" flag) opts out of
             * this default for a library/module fragment rather than a
             * complete, standalone-compilable program. See
             * sema_program_has_main's own doc comment in sema.h. */
            fprintf(stderr, "---- error: no 'main' function found in %s ----\n", g_current_filename);
            fprintf(stderr, "  (pass -c to transpile without requiring one)\n");
            rc = 1;
        } else if (is_bios && !validate_bios_constraints(g_program, g_current_filename)) {
            rc = 1;
        } else {
            /* Lowering trusts sema's results (ClassLayout, vtables, ...)
             * to be complete and correct, so it only runs once sema has
             * come back clean -- see lower_run()'s precondition in
             * lower.h. */
            if (verbosity >= 1) printf("stage 3: running lowering\n");
            int lower_errors = lower_run(g_program);
            if (verbosity >= 3) {
                lower_dump(g_program);
                lower_notes_print();
            }
            /* codegen_run() only ever reads PER-NODE annotations
             * (sema_info/lower_info) already attached directly to the
             * tree -- never the global class/typedef/free-function
             * registries sema_cleanup() frees below -- so its ordering
             * relative to that cleanup call doesn't actually matter. Runs
             * here anyway, before cleanup, to keep the "don't free
             * anything a later step might still need" discipline this
             * project settled on after the vtable-dispatch registry-
             * lifetime bug, rather than re-litigating it per call site. */
            if (verbosity >= 1) printf("stage 4: running code generator\n");
            FILE *out = (lower_errors > 0) ? NULL : fopen(output_filename, "w");
            if (lower_errors > 0) {
                fprintf(stderr, "---- %d lowering error(s) in %s ----\n", lower_errors, g_current_filename);
                rc = 1;
            } else if (out == NULL) {
                perror(output_filename);
                rc = 1;
            } else {
                codegen_run(g_program, out, verbosity >= 2);
                fclose(out);
                if (verbosity >= 1) printf("wrote generated Vircon32 C to %s\n", output_filename);
                /* Cart-packing XML: generated automatically whenever a
                 * .c file is actually written, matching v32lua's own
                 * behavior (which has no opt-out at all) -- `-x`/
                 * `--no-xml` is this project's own addition, since
                 * there was no reason not to offer one here. Runs AFTER
                 * the .c write succeeds, deliberately -- a failed XML
                 * write shouldn't undo an otherwise-successful
                 * transpile, and emit_cart_xml's own error handling
                 * already reflects that (reports to stderr, doesn't
                 * touch `rc`). */
                if (emit_xml) {
                    emit_cart_xml(output_filename, is_bios);
                    if (verbosity >= 1) {
                        char *xml_filename = replace_extension(output_filename, ".xml");
                        printf("wrote cart config to %s\n", xml_filename);
                        free(xml_filename);
                    }
                }
                /* -g: <output>.c.debug (APPENDED, not extension-swapped
                 * -- Matthew's own spec names "filename.c.debug"
                 * specifically, not "filename.debug") alongside the
                 * generated C, mapping each C line back to the C++
                 * source line that produced it. cpp_path is always
                 * input_filename (the ORIGINAL .cpp, never anything
                 * post-processed) -- deliberately, per Matthew's own
                 * note about a possible future, separate preprocessor
                 * tool: that tool would be what hands v32c++ an
                 * already-#include-resolved .cpp to transpile, and
                 * THAT filename is what belongs here once/if that
                 * exists -- not a distinction this round needs to
                 * anticipate further than recording the plain fact
                 * that this is a decision worth revisiting then. */
                if (emit_debug) {
                    size_t debug_len = strlen(output_filename) + strlen(".debug") + 1;
                    char *debug_filename = malloc(debug_len);
                    snprintf(debug_filename, debug_len, "%s.debug", output_filename);
                    if (debug_map_write(debug_filename, output_filename, input_filename)
                        && verbosity >= 1) {
                        printf("wrote debug map to %s\n", debug_filename);
                    }
                    free(debug_filename);
                }
            }
        }
        /* sema_cleanup() frees the class/typedef/free-function registries
         * sema_run() built -- deliberately called HERE, after lowering
         * has had its turn, not right after sema_run() returns above.
         * lower_run()'s vtable-dispatch phase depends on those same
         * registries (via resolve_expr_class); freeing them any earlier
         * silently breaks it -- see sema_cleanup()'s doc comment in
         * sema.h for the bug that shipped once already because of this. */
        sema_cleanup();
    } else {
        fprintf(stderr, "---- parse failed for %s ----\n", g_current_filename);
    }

    debug_map_free();
    free(derived_output);
    symtab_destroy(g_symtab);
    return rc;
}


